### ISSUE TITLE
Last used tracking for grudges

### ISSUE THREAD

**Issue by rhardih** [rhardih/ekill#21]
Since the Hit List will grow quite a lot over time, in order to make housekeeping simple, it would be good to know when a specific item on the list was last used.

Some form of option to purge very old hits might be a good idea to offer on the options page.

In order to do that, each item on the list must store a timestamp for when it was added.

----

Currently the hit list is stored as an object with this structure:

```
{
  <hostname>:
    <pathname>: [
      <selector>
      ...
    ]
    ...
  ...
}
```

However, in order to properly track selector usage, a structure more like this is probably needed:

```
{
  <hostname>:
    <pathname>: [
      {
        selector: <selector>
        lastUsed: <date>
      }
      ...
    ]
    ...
  ...
}
```

That means migration.

TODO:

- [x] Release version that simultaneously writes both the existing and the new structure, to two different local storage targets. No reads from the new structure happening yet.
- [x] When all installations have the new structure in local storage, start using the new for reads instead. *
- [x] Remove old version of structure completely from storage and code.

*Since there's no analytics built in, this will have to be based on some sort of timeline boundary; X number of days.
